language: java
python:
  - "2.7"
jdk:
  - oraclejdk8
addons:
  apt:
    packages:
      - python-pip
      - python-virtualenv
      - oracle-java8-installer
      - build-essential
      - wget
      - mercurial

# Use Trusty to get enough RAM
sudo: required
dist: trusty

env:
  global:
    - DEFAULT_VM="jvmci"
    - MX_BINARY_SUITES="jvmci,truffle"
  matrix:
    - GATE="style,fullbuild"
    - JDK="jdk8" GATE="build,test"
    - JDK="jdk8" GATE="build,bootstrap"
    - JDK="jdk9" GATE="build,test"
    - JDK="jdk9" GATE="build,bootstrap"
install:
  - |
      export MX_PATH=$TRAVIS_BUILD_DIR/../mx
      git clone https://github.com/graalvm/mx.git $MX_PATH
      export PATH=$MX_PATH/../mx:$PATH
  - |
      if [[ $GATE == *style* ]]
      then
        virtualenv venv
        source venv/bin/activate
        pip install astroid==1.1.0
        pip install pylint==1.1.0

        export ECLIPSE_TAR=$TRAVIS_BUILD_DIR/../eclipse.tar.gz
        wget https://lafo.ssw.uni-linz.ac.at/slavefiles/gate/eclipse-jdk8-linux-x86_64.tar.gz -O $ECLIPSE_TAR
        tar -C $TRAVIS_BUILD_DIR/.. -xf $ECLIPSE_TAR
        export ECLIPSE_EXE=$TRAVIS_BUILD_DIR/../eclipse/eclipse
      fi
  - |
      if [[ $GATE == *fullbuild* ]]
      then
        export JDT=$MX_PATH/ecj.jar
        wget http://ftp.halifax.rwth-aachen.de/eclipse//eclipse/downloads/drops4/R-4.5.1-201509040015/ecj-4.5.1.jar -O $JDT
      fi
  - |
      if [ "$JDK" == "jdk9" ]
      then
        JDK_TAR=$TRAVIS_BUILD_DIR/../jdk9-SNAPSHOT-release-linux-amd64.tar.gz
        wget https://lafo.ssw.uni-linz.ac.at/slavefiles/jdk/jdk9-SNAPSHOT-release-linux-amd64.tar.gz -O $JDK_TAR
        tar -C $TRAVIS_BUILD_DIR/.. -xf $JDK_TAR
        export JAVA_HOME=$TRAVIS_BUILD_DIR/../jdk1.9.0
      fi
script:
  - mx --strict-compliance gate --strict-mode --tags $GATE
after_failure:
  - cat hs_err*
